/* NOTE: Do not edit this file, it is generated by a script:
   E.py --api gl 4.4 --api wgl 4.4 --api glx 4.4 --api cgl 1.4 --api egl 1.0 --outdir .
*/

/*
  Copyright (c) 2011-2013 NVIDIA Corporation
  Copyright (c) 2011-2013 Cass Everitt
  Copyright (c) 2012-2013 Scott Nations
  Copyright (c) 2012 Mathias Schott
  Copyright (c) 2012-2013 Nigel Stewart
  Copyright (c) 2012-2013 Google Inc.
  All rights reserved.

  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:

    Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

    Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
  OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/*
  Intended formatting conventions:
  $ astyle --style=allman --indent=spaces=2 --indent-switches
*/

#ifndef REGAL_EMU_PROCS_SO_H
#define REGAL_EMU_PROCS_SO_H

#include "RegalUtil.h"

#if REGAL_EMULATION

REGAL_GLOBAL_BEGIN

#include "RegalPrivate.h"
#include "RegalContext.h"
#include "RegalDispatch.h"

REGAL_GLOBAL_END

REGAL_NAMESPACE_BEGIN

void EmuProcsInterceptSo( Dispatch::GL & dt );

struct EmuProcsOriginateSo {

  EmuProcsOriginateSo() {
    memset(this, 0, sizeof( *this ) );
  }

  REGALGLACTIVETEXTUREPROC glActiveTexture;
  REGALGLACTIVETEXTUREARBPROC glActiveTextureARB;
  REGALGLBINDSAMPLERPROC glBindSampler;
  REGALGLBINDTEXTUREPROC glBindTexture;
  REGALGLDELETESAMPLERSPROC glDeleteSamplers;
  REGALGLDELETETEXTURESPROC glDeleteTextures;
  REGALGLDRAWARRAYSPROC glDrawArrays;
  REGALGLDRAWARRAYSEXTPROC glDrawArraysEXT;
  REGALGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
  REGALGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
  REGALGLDRAWARRAYSINSTANCEDARBPROC glDrawArraysInstancedARB;
  REGALGLDRAWARRAYSINSTANCEDEXTPROC glDrawArraysInstancedEXT;
  REGALGLDRAWELEMENTARRAYAPPLEPROC glDrawElementArrayAPPLE;
  REGALGLDRAWELEMENTARRAYATIPROC glDrawElementArrayATI;
  REGALGLDRAWELEMENTSPROC glDrawElements;
  REGALGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
  REGALGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
  REGALGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
  REGALGLDRAWELEMENTSINSTANCEDARBPROC glDrawElementsInstancedARB;
  REGALGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
  REGALGLDRAWELEMENTSINSTANCEDEXTPROC glDrawElementsInstancedEXT;
  REGALGLDRAWRANGEELEMENTARRAYAPPLEPROC glDrawRangeElementArrayAPPLE;
  REGALGLDRAWRANGEELEMENTARRAYATIPROC glDrawRangeElementArrayATI;
  REGALGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
  REGALGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
  REGALGLDRAWRANGEELEMENTSEXTPROC glDrawRangeElementsEXT;
  REGALGLGENSAMPLERSPROC glGenSamplers;
  REGALGLGENTEXTURESPROC glGenTextures;
  REGALGLGETDOUBLEVPROC glGetDoublev;
  REGALGLGETFLOATVPROC glGetFloatv;
  REGALGLGETINTEGER64VPROC glGetInteger64v;
  REGALGLGETINTEGERVPROC glGetIntegerv;
  REGALGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
  REGALGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
  REGALGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
  REGALGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
  REGALGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
  REGALGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
  REGALGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
  REGALGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
  REGALGLISSAMPLERPROC glIsSampler;
  REGALGLMULTIDRAWARRAYSPROC glMultiDrawArrays;
  REGALGLMULTIDRAWARRAYSEXTPROC glMultiDrawArraysEXT;
  REGALGLMULTIDRAWARRAYSINDIRECTPROC glMultiDrawArraysIndirect;
  REGALGLMULTIDRAWARRAYSINDIRECTAMDPROC glMultiDrawArraysIndirectAMD;
  REGALGLMULTIDRAWELEMENTARRAYAPPLEPROC glMultiDrawElementArrayAPPLE;
  REGALGLMULTIDRAWELEMENTSPROC glMultiDrawElements;
  REGALGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex;
  REGALGLMULTIDRAWELEMENTSEXTPROC glMultiDrawElementsEXT;
  REGALGLMULTIDRAWELEMENTSINDIRECTPROC glMultiDrawElementsIndirect;
  REGALGLMULTIDRAWELEMENTSINDIRECTAMDPROC glMultiDrawElementsIndirectAMD;
  REGALGLMULTIDRAWRANGEELEMENTARRAYAPPLEPROC glMultiDrawRangeElementArrayAPPLE;
  REGALGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
  REGALGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
  REGALGLSAMPLERPARAMETERFPROC glSamplerParameterf;
  REGALGLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
  REGALGLSAMPLERPARAMETERIPROC glSamplerParameteri;
  REGALGLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
  REGALGLTEXPARAMETERIIVPROC glTexParameterIiv;
  REGALGLTEXPARAMETERIIVEXTPROC glTexParameterIivEXT;
  REGALGLTEXPARAMETERIUIVPROC glTexParameterIuiv;
  REGALGLTEXPARAMETERIUIVEXTPROC glTexParameterIuivEXT;
  REGALGLTEXPARAMETERFPROC glTexParameterf;
  REGALGLTEXPARAMETERFVPROC glTexParameterfv;
  REGALGLTEXPARAMETERIPROC glTexParameteri;
  REGALGLTEXPARAMETERIVPROC glTexParameteriv;

  void Initialize( Dispatch::GL & dt ) {
    glActiveTexture = dt.glActiveTexture;
    glActiveTextureARB = dt.glActiveTextureARB;
    glBindSampler = dt.glBindSampler;
    glBindTexture = dt.glBindTexture;
    glDeleteSamplers = dt.glDeleteSamplers;
    glDeleteTextures = dt.glDeleteTextures;
    glDrawArrays = dt.glDrawArrays;
    glDrawArraysEXT = dt.glDrawArraysEXT;
    glDrawArraysIndirect = dt.glDrawArraysIndirect;
    glDrawArraysInstanced = dt.glDrawArraysInstanced;
    glDrawArraysInstancedARB = dt.glDrawArraysInstancedARB;
    glDrawArraysInstancedEXT = dt.glDrawArraysInstancedEXT;
    glDrawElementArrayAPPLE = dt.glDrawElementArrayAPPLE;
    glDrawElementArrayATI = dt.glDrawElementArrayATI;
    glDrawElements = dt.glDrawElements;
    glDrawElementsBaseVertex = dt.glDrawElementsBaseVertex;
    glDrawElementsIndirect = dt.glDrawElementsIndirect;
    glDrawElementsInstanced = dt.glDrawElementsInstanced;
    glDrawElementsInstancedARB = dt.glDrawElementsInstancedARB;
    glDrawElementsInstancedBaseVertex = dt.glDrawElementsInstancedBaseVertex;
    glDrawElementsInstancedEXT = dt.glDrawElementsInstancedEXT;
    glDrawRangeElementArrayAPPLE = dt.glDrawRangeElementArrayAPPLE;
    glDrawRangeElementArrayATI = dt.glDrawRangeElementArrayATI;
    glDrawRangeElements = dt.glDrawRangeElements;
    glDrawRangeElementsBaseVertex = dt.glDrawRangeElementsBaseVertex;
    glDrawRangeElementsEXT = dt.glDrawRangeElementsEXT;
    glGenSamplers = dt.glGenSamplers;
    glGenTextures = dt.glGenTextures;
    glGetDoublev = dt.glGetDoublev;
    glGetFloatv = dt.glGetFloatv;
    glGetInteger64v = dt.glGetInteger64v;
    glGetIntegerv = dt.glGetIntegerv;
    glGetSamplerParameterIiv = dt.glGetSamplerParameterIiv;
    glGetSamplerParameterIuiv = dt.glGetSamplerParameterIuiv;
    glGetSamplerParameterfv = dt.glGetSamplerParameterfv;
    glGetSamplerParameteriv = dt.glGetSamplerParameteriv;
    glGetTexParameterIiv = dt.glGetTexParameterIiv;
    glGetTexParameterIuiv = dt.glGetTexParameterIuiv;
    glGetTexParameterfv = dt.glGetTexParameterfv;
    glGetTexParameteriv = dt.glGetTexParameteriv;
    glIsSampler = dt.glIsSampler;
    glMultiDrawArrays = dt.glMultiDrawArrays;
    glMultiDrawArraysEXT = dt.glMultiDrawArraysEXT;
    glMultiDrawArraysIndirect = dt.glMultiDrawArraysIndirect;
    glMultiDrawArraysIndirectAMD = dt.glMultiDrawArraysIndirectAMD;
    glMultiDrawElementArrayAPPLE = dt.glMultiDrawElementArrayAPPLE;
    glMultiDrawElements = dt.glMultiDrawElements;
    glMultiDrawElementsBaseVertex = dt.glMultiDrawElementsBaseVertex;
    glMultiDrawElementsEXT = dt.glMultiDrawElementsEXT;
    glMultiDrawElementsIndirect = dt.glMultiDrawElementsIndirect;
    glMultiDrawElementsIndirectAMD = dt.glMultiDrawElementsIndirectAMD;
    glMultiDrawRangeElementArrayAPPLE = dt.glMultiDrawRangeElementArrayAPPLE;
    glSamplerParameterIiv = dt.glSamplerParameterIiv;
    glSamplerParameterIuiv = dt.glSamplerParameterIuiv;
    glSamplerParameterf = dt.glSamplerParameterf;
    glSamplerParameterfv = dt.glSamplerParameterfv;
    glSamplerParameteri = dt.glSamplerParameteri;
    glSamplerParameteriv = dt.glSamplerParameteriv;
    glTexParameterIiv = dt.glTexParameterIiv;
    glTexParameterIivEXT = dt.glTexParameterIivEXT;
    glTexParameterIuiv = dt.glTexParameterIuiv;
    glTexParameterIuivEXT = dt.glTexParameterIuivEXT;
    glTexParameterf = dt.glTexParameterf;
    glTexParameterfv = dt.glTexParameterfv;
    glTexParameteri = dt.glTexParameteri;
    glTexParameteriv = dt.glTexParameteriv;
  }
};

REGAL_NAMESPACE_END

#endif // REGAL_EMULATION

#endif // REGAL_EMU_PROCS_SO_H
